import { describe, expect, it } from "vitest";
import { applyGraphqlIdentity, graphqlIdentity } from "../graphql";

describe("graphqlIdentity", () => {
  it("reads the declared operation name and type", () => {
    expect(
      graphqlIdentity(
        JSON.stringify({
          operationName: "UpdateCart",
          query: "mutation UpdateCart($id: ID!) { updateCart(id: $id) { id } }",
          variables: { id: "1" },
        }),
      ),
    ).toEqual({ op: "mutation", name: "UpdateCart" });
  });

  it("recovers the name from the document when the request does not declare one", () => {
    expect(
      graphqlIdentity(
        JSON.stringify({ query: "query Orders { orders { id } }" }),
      ),
    ).toEqual({ op: "query", name: "Orders" });
  });

  it("reports an anonymous operation by type alone", () => {
    expect(graphqlIdentity(JSON.stringify({ query: "mutation { pay { id } }" })))
      .toEqual({ op: "mutation" });
  });

  it("treats a bare selection set as an anonymous query", () => {
    expect(graphqlIdentity(JSON.stringify({ query: "{ me { id } }" }))).toEqual({
      op: "query",
    });
  });

  it("looks past leading comments and whitespace", () => {
    expect(
      graphqlIdentity(
        JSON.stringify({
          query: "\n  # generated by codegen\n  subscription Ticks { ticks }",
        }),
      ),
    ).toEqual({ op: "subscription", name: "Ticks" });
  });

  // A batch is one HTTP request doing several things. Naming it after the first operation without
  // saying it was a batch would be a smaller lie than the URL told, but still a lie.
  it("names a batch by its first operation and says how many", () => {
    expect(
      graphqlIdentity(
        JSON.stringify([
          { query: "query A { a }" },
          { query: "query B { b }" },
        ]),
      ),
    ).toEqual({ op: "query", name: "A", batch: 2 });
  });

  // Persisted queries send no document at all. The type is genuinely unknown and is not guessed: a
  // persisted mutation reported as a query would be worse than silence.
  it("identifies a persisted query without inventing its type", () => {
    expect(
      graphqlIdentity(
        JSON.stringify({
          operationName: "Orders",
          extensions: { persistedQuery: { version: 1, sha256Hash: "abc" } },
        }),
      ),
    ).toEqual({ op: "unknown", name: "Orders" });
  });

  it("ignores an ordinary JSON request", () => {
    expect(
      graphqlIdentity(JSON.stringify({ email: "a@b.test", qty: 2 })),
    ).toBeUndefined();
  });

  it("ignores a body that is not JSON at all", () => {
    expect(graphqlIdentity("qty=2&sku=ABC")).toBeUndefined();
  });

  // The keyword has to be the operation keyword, not a word that happens to appear in the document.
  it("does not mistake a field named mutation for an operation", () => {
    expect(
      graphqlIdentity(JSON.stringify({ query: '{ log(kind: "mutation") { id } }' })),
    ).toEqual({ op: "query" });
  });

  // Variables carry user input. Nothing here reads them; the body redaction that runs over them is
  // the only thing entitled to decide what survives.
  it("never carries variables into the identity", () => {
    const identity = graphqlIdentity(
      JSON.stringify({
        query: "mutation Pay { pay { id } }",
        variables: { cardNumber: "4111111111111111" },
      }),
    );

    expect(JSON.stringify(identity)).not.toContain("4111111111111111");
  });
});

describe("applyGraphqlIdentity", () => {
  it("stamps the identity on the event payload", () => {
    const target: Record<string, unknown> = {};
    applyGraphqlIdentity(target, JSON.stringify({ query: "query Me { me }" }));

    expect(target.gql).toEqual({ op: "query", name: "Me" });
  });

  it("leaves a non-GraphQL request untouched", () => {
    const target: Record<string, unknown> = {};
    applyGraphqlIdentity(target, JSON.stringify({ qty: 1 }));
    applyGraphqlIdentity(target, undefined);

    expect(target).toEqual({});
  });
});
