import {
  buildApplicationAssertionEvent,
  MAX_APPLICATION_ASSERTIONS_PER_SESSION,
  type ApplicationAssertionOptions,
  type ApplicationAssertionResult,
} from "crumbtrail-core";
import { getProcessSessionId } from "./process-session";
import {
  sendBackendEvent,
  type SendBackendEventOptions,
} from "./backend-intake";
import { readRequestCorrelation } from "./request-context";

export interface SendApplicationAssertionOptions
  extends Omit<SendBackendEventOptions, "event" | "sessionId">,
    Omit<ApplicationAssertionOptions, "sessionId" | "requestId"> {
  sessionId?: string;
  requestId?: string;
}

export interface SendApplicationAssertionResult
  extends ApplicationAssertionResult {
  /** Whether the valid event reached the intake. */
  delivered?: boolean;
}

// Session identifiers are generated by the SDK and therefore naturally rotate.
// Keep the accounting map bounded as a process serves many short lived sessions.
const assertionCounts = new Map<string, number>();
const MAX_TRACKED_ASSERTION_SESSIONS = 1_000;

function consumeAssertionSlot(sessionId: string): boolean {
  const count = assertionCounts.get(sessionId) ?? 0;
  if (count >= MAX_APPLICATION_ASSERTIONS_PER_SESSION) return false;
  assertionCounts.set(sessionId, count + 1);
  if (assertionCounts.size > MAX_TRACKED_ASSERTION_SESSIONS) {
    const oldest = assertionCounts.keys().next().value;
    if (typeof oldest === "string") assertionCounts.delete(oldest);
  }
  return true;
}

/** Clear accounting between isolated tests or an embedding's process restart. */
export function resetApplicationAssertionCountsForTests(): void {
  assertionCounts.clear();
}

/**
 * Build and send one bounded application assertion from a Node request or job.
 * Request context is filled in automatically when the call runs inside a
 * correlated request. The process session is the fallback for background work.
 */
export async function sendApplicationAssertion(
  options: SendApplicationAssertionOptions,
): Promise<SendApplicationAssertionResult> {
  const requestCorrelation = readRequestCorrelation();
  const sessionId =
    options.sessionId ??
    requestCorrelation?.sessionId ??
    getProcessSessionId();
  const requestId = options.requestId ?? requestCorrelation?.requestId;
  if (!sessionId) {
    return {
      accepted: false,
      rejection: "correlation_invalid",
    };
  }
  const built = buildApplicationAssertionEvent(
    {
      name: options.name,
      operator: options.operator,
      expected: options.expected,
      actual: options.actual,
      sessionId,
      ...(requestId === undefined ? {} : { requestId }),
      ...(options.traceId === undefined ? {} : { traceId: options.traceId }),
    },
    Date.now(),
  );
  if (!built.accepted || built.event === undefined) {
    // This branch is deliberately before the cap and sendBackendEvent, so
    // malformed data neither consumes a slot nor reaches the wire.
    return built;
  }
  if (!consumeAssertionSlot(sessionId)) {
    return {
      accepted: false,
      rejection: "session_cap_reached",
    };
  }

  const delivered = await sendBackendEvent({
    ...options,
    event: built.event,
    sessionId,
  });
  return { ...built, delivered };
}

export const sendSupportAssertion = sendApplicationAssertion;
export const recordApplicationAssertion = sendApplicationAssertion;
