import {
  buildApplicationAssertionEvent,
  MAX_APPLICATION_ASSERTIONS_PER_SESSION,
  type ApplicationAssertionOptions,
  type ApplicationAssertionResult,
} from "crumbtrail-core";
import { getProcessSessionId } from "./process-session";
import {
  sendBackendEvent,
  type SendBackendEventOptions,
} from "./backend-intake";
import { readRequestCorrelation } from "./request-context";

export interface SendApplicationAssertionOptions
  extends
    Omit<SendBackendEventOptions, "event" | "sessionId">,
    Omit<ApplicationAssertionOptions, "sessionId" | "requestId"> {
  sessionId?: string;
  requestId?: string;
}

export interface SendApplicationAssertionResult extends ApplicationAssertionResult {
  /** Whether the valid event reached the intake. */
  delivered?: boolean;
}

type AssertionSessionState = {
  count: number;
};

type TransportSnapshot = Omit<SendBackendEventOptions, "event" | "sessionId">;

type AssertionSnapshot = {
  assertion: ApplicationAssertionOptions;
  transport: TransportSnapshot;
};

type SnapshotResult =
  | { accepted: true; snapshot: AssertionSnapshot }
  | { accepted: false; result: ApplicationAssertionResult };

// Session identifiers are generated by the SDK and therefore naturally rotate.
// Keep the accounting map bounded as a process serves many short-lived sessions.
const assertionSessions = new Map<string, AssertionSessionState>();
const MAX_TRACKED_ASSERTION_SESSIONS = 1_000;

function isPlainRecord(value: unknown): value is Record<string, unknown> {
  if (value === null || typeof value !== "object")
    return false;
  try {
    if (Array.isArray(value)) return false;
    const prototype = Object.getPrototypeOf(value);
    return prototype === Object.prototype || prototype === null;
  } catch {
    return false;
  }
}

function readOwn(record: Record<string, unknown>, key: string): unknown {
  return Object.prototype.hasOwnProperty.call(record, key)
    ? record[key]
    : undefined;
}

/** Snapshot assertion and transport fields once, without spreading caller input. */
function snapshotOptions(input: unknown): SnapshotResult {
  if (!isPlainRecord(input)) {
    return {
      accepted: false,
      result: { accepted: false, rejection: "invalid_options" },
    };
  }
  try {
    const assertion: ApplicationAssertionOptions = {
      name: readOwn(input, "name") as string,
      operator: readOwn(
        input,
        "operator",
      ) as ApplicationAssertionOptions["operator"],
      expected: readOwn(
        input,
        "expected",
      ) as ApplicationAssertionOptions["expected"],
      actual: readOwn(input, "actual") as ApplicationAssertionOptions["actual"],
    };
    const requestId = readOwn(input, "requestId");
    const traceId = readOwn(input, "traceId");
    const sessionId = readOwn(input, "sessionId");
    if (requestId !== undefined) assertion.requestId = requestId as string;
    if (traceId !== undefined) assertion.traceId = traceId as string;
    if (sessionId !== undefined) assertion.sessionId = sessionId as string;

    const transport: TransportSnapshot = {};
    const endpoint = readOwn(input, "endpoint");
    const authToken = readOwn(input, "authToken");
    const fetch = readOwn(input, "fetch");
    const signal = readOwn(input, "signal");
    const onWarning = readOwn(input, "onWarning");
    const retries = readOwn(input, "retries");
    const retryDelayMs = readOwn(input, "retryDelayMs");
    const sleep = readOwn(input, "sleep");
    if (
      (endpoint !== undefined && typeof endpoint !== "string") ||
      (authToken !== undefined && typeof authToken !== "string") ||
      (fetch !== undefined && typeof fetch !== "function") ||
      (onWarning !== undefined && typeof onWarning !== "function") ||
      (sleep !== undefined && typeof sleep !== "function") ||
      (signal !== undefined &&
        (typeof signal !== "object" || signal === null)) ||
      (retries !== undefined &&
        (typeof retries !== "number" || !Number.isFinite(retries))) ||
      (retryDelayMs !== undefined &&
        (typeof retryDelayMs !== "number" || !Number.isFinite(retryDelayMs)))
    )
      return {
        accepted: false,
        result: { accepted: false, rejection: "invalid_options" },
      };
    if (endpoint !== undefined) transport.endpoint = endpoint as string;
    if (authToken !== undefined) transport.authToken = authToken as string;
    if (fetch !== undefined)
      transport.fetch = fetch as TransportSnapshot["fetch"];
    if (signal !== undefined) transport.signal = signal as AbortSignal;
    if (onWarning !== undefined)
      transport.onWarning = onWarning as TransportSnapshot["onWarning"];
    if (retries !== undefined) transport.retries = retries as number;
    if (retryDelayMs !== undefined)
      transport.retryDelayMs = retryDelayMs as number;
    if (sleep !== undefined)
      transport.sleep = sleep as TransportSnapshot["sleep"];
    return { accepted: true, snapshot: { assertion, transport } };
  } catch {
    return {
      accepted: false,
      result: { accepted: false, rejection: "invalid_options" },
    };
  }
}

function consumeAssertionSlot(
  sessionId: string,
): "accepted" | "session_cap_reached" | "session_tracking_limit_reached" {
  const state = assertionSessions.get(sessionId);
  if (state) {
    if (state.count >= MAX_APPLICATION_ASSERTIONS_PER_SESSION)
      return "session_cap_reached";
    state.count += 1;
    return "accepted";
  }
  if (assertionSessions.size >= MAX_TRACKED_ASSERTION_SESSIONS)
    return "session_tracking_limit_reached";
  assertionSessions.set(sessionId, { count: 1 });
  return "accepted";
}

/** Release accounting for an explicit or manually managed assertion session. */
export function endApplicationAssertionSession(sessionId: string): void {
  if (typeof sessionId !== "string" || sessionId.length === 0) return;
  assertionSessions.delete(sessionId);
}

/** Internal lifecycle hook for the process-owned auto-capture session. */
export function clearApplicationAssertionSession(sessionId: string): void {
  endApplicationAssertionSession(sessionId);
}

/** Clear accounting between isolated tests or an embedding's process restart. */
export function resetApplicationAssertionCountsForTests(): void {
  assertionSessions.clear();
}

/**
 * Build and send one bounded application assertion from a Node request or job.
 * Request context is filled in automatically when the call runs inside a
 * correlated request. The process session is the fallback for background work.
 */
export async function sendApplicationAssertion(
  options: SendApplicationAssertionOptions,
): Promise<SendApplicationAssertionResult> {
  const snapshot = snapshotOptions(options);
  if (!snapshot.accepted) return snapshot.result;
  const { assertion, transport } = snapshot.snapshot;
  const requestCorrelation = readRequestCorrelation();
  const requestedSessionId = assertion.sessionId;
  const sessionId =
    requestedSessionId ??
    requestCorrelation?.sessionId ??
    getProcessSessionId();
  const requestId = assertion.requestId ?? requestCorrelation?.requestId;
  if (!sessionId) {
    return {
      accepted: false,
      rejection: "correlation_invalid",
    };
  }
  const built = buildApplicationAssertionEvent(
    {
      name: assertion.name,
      operator: assertion.operator,
      expected: assertion.expected,
      actual: assertion.actual,
      sessionId,
      ...(requestId === undefined ? {} : { requestId }),
      ...(assertion.traceId === undefined
        ? {}
        : { traceId: assertion.traceId }),
    },
    Date.now(),
  );
  if (!built.accepted || built.event === undefined) {
    // This branch is deliberately before the cap and sendBackendEvent, so
    // malformed data neither consumes a slot nor reaches the wire.
    return built;
  }
  const admission = consumeAssertionSlot(sessionId);
  if (admission !== "accepted") {
    return {
      accepted: false,
      rejection: admission,
    };
  }

  const delivered = await sendBackendEvent({
    ...transport,
    event: built.event,
    sessionId,
  });
  return { ...built, delivered };
}

export const sendSupportAssertion = sendApplicationAssertion;
export const recordApplicationAssertion = sendApplicationAssertion;
