import {
  buildApplicationAssertionEvent,
  MAX_APPLICATION_ASSERTIONS_PER_SESSION,
  type ApplicationAssertionOptions,
  type ApplicationAssertionResult,
} from "crumbtrail-core";
import { getProcessSessionId } from "./process-session";
import {
  sendBackendEvent,
  type SendBackendEventOptions,
} from "./backend-intake";
import { readRequestCorrelation } from "./request-context";

export interface SendApplicationAssertionOptions
  extends
    Omit<SendBackendEventOptions, "event" | "sessionId">,
    Omit<ApplicationAssertionOptions, "sessionId" | "requestId"> {
  sessionId?: string;
  requestId?: string;
}

export interface SendApplicationAssertionResult extends ApplicationAssertionResult {
  /** Whether the valid event reached the intake. */
  delivered?: boolean;
}

// Session identifiers are generated by the SDK and therefore naturally rotate.
// Keep the accounting map bounded as a process serves many short lived sessions.
// Entries are never evicted implicitly: an unknown session is rejected once the
// table is full so an active session can never lose its cap.
const assertionCounts = new Map<string, number>();
const MAX_TRACKED_ASSERTION_SESSIONS = 1_000;

function consumeAssertionSlot(
  sessionId: string,
): "accepted" | "session_cap_reached" | "session_tracking_limit_reached" {
  const count = assertionCounts.get(sessionId);
  if (count !== undefined) {
    if (count >= MAX_APPLICATION_ASSERTIONS_PER_SESSION)
      return "session_cap_reached";
    assertionCounts.set(sessionId, count + 1);
    return "accepted";
  }
  if (assertionCounts.size >= MAX_TRACKED_ASSERTION_SESSIONS)
    return "session_tracking_limit_reached";
  assertionCounts.set(sessionId, 1);
  return "accepted";
}

/** Release accounting for a process-owned session after its capture ends. */
export function clearApplicationAssertionSession(sessionId: string): void {
  assertionCounts.delete(sessionId);
}

/** Clear accounting between isolated tests or an embedding's process restart. */
export function resetApplicationAssertionCountsForTests(): void {
  assertionCounts.clear();
}

/**
 * Build and send one bounded application assertion from a Node request or job.
 * Request context is filled in automatically when the call runs inside a
 * correlated request. The process session is the fallback for background work.
 */
export async function sendApplicationAssertion(
  options: SendApplicationAssertionOptions,
): Promise<SendApplicationAssertionResult> {
  const requestCorrelation = readRequestCorrelation();
  const sessionId =
    options.sessionId ?? requestCorrelation?.sessionId ?? getProcessSessionId();
  const requestId = options.requestId ?? requestCorrelation?.requestId;
  if (!sessionId) {
    return {
      accepted: false,
      rejection: "correlation_invalid",
    };
  }
  const built = buildApplicationAssertionEvent(
    {
      name: options.name,
      operator: options.operator,
      expected: options.expected,
      actual: options.actual,
      sessionId,
      ...(requestId === undefined ? {} : { requestId }),
      ...(options.traceId === undefined ? {} : { traceId: options.traceId }),
    },
    Date.now(),
  );
  if (!built.accepted || built.event === undefined) {
    // This branch is deliberately before the cap and sendBackendEvent, so
    // malformed data neither consumes a slot nor reaches the wire.
    return built;
  }
  const admission = consumeAssertionSlot(sessionId);
  if (admission !== "accepted") {
    return {
      accepted: false,
      rejection: admission,
    };
  }

  const delivered = await sendBackendEvent({
    ...options,
    event: built.event,
    sessionId,
  });
  return { ...built, delivered };
}

export const sendSupportAssertion = sendApplicationAssertion;
export const recordApplicationAssertion = sendApplicationAssertion;
